### ISSUE TITLE
Help! ** Don't have a product spec for: 'omni_sharkl2' ** Do you have the right repo manifest?

### ISSUE THREAD

**Issue by MenuuTUX** [PitchBlackRecoveryProject/manifest_pb#10]
`aqua@aqua-HP-EliteBook-8460p:~/PitchBlack$ lunch omni_sharkl2-eng
build/core/envsetup.mk:223: *** No config file found for TARGET_DEVICE sharkl2.  Stop.
android-8.1
your device can't be found in device sources..
Traceback (most recent call last):
  File "vendor/pb/build/tools/roomservice.py", line 428, in <module>
    fetch_device(device)
  File "vendor/pb/build/tools/roomservice.py", line 398, in fetch_device
    git_data = search_github_for_device(device)
  File "vendor/pb/build/tools/roomservice.py", line 78, in search_github_for_device
    check_repo_exists(git_data)
  File "vendor/pb/build/tools/roomservice.py", line 63, in check_repo_exists
    "roomservice".format(device, android_team))
Exception: sharkl2 not found in PitchBlackRecoveryProject Github, exiting roomservice
build/core/envsetup.mk:223: *** No config file found for TARGET_DEVICE sharkl2.  Stop.

** Don't have a product spec for: 'omni_sharkl2'
** Do you have the right repo manifest?
`

**Comment by manjotsidhu** [comment]
> `aqua@aqua-HP-EliteBook-8460p:~/PitchBlack$ lunch omni_sharkl2-eng
> build/core/envsetup.mk:223: *** No config file found for TARGET_DEVICE sharkl2. Stop.
> android-8.1
> your device can't be found in device sources..
> Traceback (most recent call last):
> File "vendor/pb/build/tools/roomservice.py", line 428, in
> fetch_device(device)
> File "vendor/pb/build/tools/roomservice.py", line 398, in fetch_device
> git_data = search_github_for_device(device)
> File "vendor/pb/build/tools/roomservice.py", line 78, in search_github_for_device
> check_repo_exists(git_data)
> File "vendor/pb/build/tools/roomservice.py", line 63, in check_repo_exists
> "roomservice".format(device, android_team))
> Exception: sharkl2 not found in PitchBlackRecoveryProject Github, exiting roomservice
> build/core/envsetup.mk:223: *** No config file found for TARGET_DEVICE sharkl2. Stop.
> 
> ** Don't have a product spec for: 'omni_sharkl2'
> ** Do you have the right repo manifest?
> `

Please send link to your device tree

**Comment by DelightReza** [comment]
@friendlymaninthisworld https://github.com/friendlymaninthisworld/twrp_device_maxwest_sharkl2/pull/1 merge it

**Comment by MenuuTUX** [comment]
>
> Please send link to your device tree
>
Wow thanks for the reply @manjotsidhu ! Someone made a device tree for me : 
https://github.com/friendlymaninthisworld/twrp_device_maxwest_sharkl
^ I just forked it.

**Comment by MenuuTUX** [comment]
> @friendlymaninthisworld [friendlymaninthisworld/twrp_device_maxwest_sharkl2#1](https://github.com/friendlymaninthisworld/twrp_device_maxwest_sharkl2/pull/1) merge it

How do I do that? Sorry I don't really use git hub that often. Could you link a tutorial or just list the steps?

**Comment by manjotsidhu** [comment]
> > @friendlymaninthisworld [friendlymaninthisworld/twrp_device_maxwest_sharkl2#1](https://github.com/friendlymaninthisworld/twrp_device_maxwest_sharkl2/pull/1) merge it
> 
> How do I do that? Sorry I don't really use git hub that often. Could you link a tutorial or just list the steps?

Kindly send the device tree you are using to compile

**Comment by MenuuTUX** [comment]
I think you missed it: 
https://github.com/friendlymaninthisworld/twrp_device_maxwest_sharkl

**Comment by friendlymaninthisworld** [comment]
Hello?

**Comment by DelightReza** [comment]
> > @friendlymaninthisworld [friendlymaninthisworld/twrp_device_maxwest_sharkl2#1](https://github.com/friendlymaninthisworld/twrp_device_maxwest_sharkl2/pull/1) merge it
> 
> How do I do that? Sorry I don't really use git hub that often. Could you link a tutorial or just list the steps?

Edit that changes manually then

**Comment by MenuuTUX** [comment]
> 
> Edit that changes manually then
>
Are you talking about the 2 changes you made on "omni_sharkl2.mk" ? Yea I edited them manually. But I still get the error, and I still don't know what or how to merge repositories in git hub. 

Can a tutorial like this help me? https://saintgimp.org/2013/01/22/merging-two-git-repositories-into-one-repository-without-losing-file-history/

**Comment by MenuuTUX** [comment]
hello? I still need a bit of help.

**Comment by manjotsidhu** [comment]
> hello? I still need a bit of help.

After doing those changes, again do `. build/envsetup.sh` and lunch command.

**Comment by MenuuTUX** [comment]
Thanks it worked!
