### ISSUE TITLE
Lancelot (Redmi 9) restore issue

### ISSUE THREAD

**Issue by ghost** [PitchBlackRecoveryProject/manifest_pb#15]
With pbrp 3.0 restore function works well but on pbrp 3.1 i build it with offical pbrp tree for lancelot .build was successful but problem is i cannot restore ..it stuck..any help or i did something wrong ?

**Comment by SathamHussainM** [comment]
Plz share logs and tree in our group

**Comment by ghost** [comment]
I submitted but no reply

**Comment by SathamHussainM** [comment]
Can you plz share again and tag admins.

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
Here my post
https://t.me/pbrpcom/74671

No valuable replay
