### ISSUE TITLE
weaver and magisk prebuild on branch twrp-7.1

### ISSUE THREAD

**Issue by fzkangga** [PitchBlackRecoveryProject/manifest_pb#3]
missing magisk prebuild and android.hardware.weaver@1.0 on branch twrp-7.1

**Comment by AndroiableDroid** [comment]
Lets check

**Comment by AndroiableDroid** [comment]
think Fixed
check

**Comment by RebelLion420** [comment]
Still getting android.hardware.weaver@1.0 missing error on twrp-7.1. Any ideas how to fix? I tried exporting ALLOW_MISSING_DEPENDENCIES and I have toolbox instead of busybox in BoardConfig
