### ISSUE TITLE
Cannot recovery boot

### ISSUE THREAD

**Issue by hosytan** [PitchBlackRecoveryProject/manifest_pb#4]
I built PBR for Xiaomi Redmi 7 (onclite) as following:
```
$ repo init -u git://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-9.0
$ repo sync
$ mkdir -p device/xiaomi
$ git clone https://github.com/PitchBlackRecoveryProject/android-device-xiaomi-onclite-pbrp.git  device/xiaomi/onclite
$ . build/envsetup.sh
$ lunch omni_onclite-eng
$ mka recoveryimage
```
It make the .img
```
****************************************************************************************
* BUILD SUCCESSFUL
* RECOVERY LOCATION: ./out/target/product/onclite/recovery.img
* RECOVERY SIZE: 33M
* ZIP LOCATION: ./out/target/product/onclite/PitchBlack-onclite-2.9.0-20200324-1211-UNOFFICIAL.zip
* ZIP SIZE: 54M
****************************************************************************************

#### build completed successfully (09:54 (mm:ss)) ####
```
$` fastboot flash recovery recovery.img`

But it cannot boot, stop on splash logo.
Any idea?

**Comment by hosytan** [comment]
If I use your release as https://sourceforge.net/projects/pitchblack-twrp/files/onclite/PitchBlack-onclite-2.9.0-20190624-0606-OFFICIAL.zip/download.
I can boot to recovery with same flastboot.

Maybe my build method had problem? Need your help.

**Comment by rokibhasansagar** [comment]
> ```
> $ git clone https://github.com/PitchBlackRecoveryProject/android-device-xiaomi-onclite-pbrp.git  device/xiaomi/onclite
> $ . build/envsetup.sh
> $ lunch omni_onclite-eng
> $ mka recoveryimage
> ```

Device tree in PBRP ORG is not yet updated.
Try the Base DT from here and build: https://github.com/AshuSharma7/android_device_xiaomi_onclite-twrp

**Comment by rokibhasansagar** [comment]
@SamwellHo 
Built a new one, [Test Build](https://github.com/PitchBlackRecoveryProject/android-device-xiaomi-onclite-pbrp/tree/2.9.0-test)

Check if it boots.
Give feedback on Telegram Group.

**Comment by hosytan** [comment]
Thanks, but no luck, it cannot boot. Stop on splash logo after booting to recovery.

**Comment by hosytan** [comment]
If I user your release as https://sourceforge.net/projects/pitchblack-twrp/files/onclite/.
I can boot to PBR recovery.
But I cannot boot if I use my build. Don't know why.

**Comment by manjotsidhu** [comment]
@SamwellHo Try https://github.com/PitchBlackRecoveryProject/android_device_xiaomi_onc-pbrp
