### ISSUE TITLE
Need to be authorized repo sync？

### ISSUE THREAD

**Issue by xintiaoxuanlv** [PitchBlackRecoveryProject/manifest_pb#9]
repo init -u git：//github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-10.0
fatal: 'git：//github.com/PitchBlackRecoveryProject/manifest_pb.git' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**Comment by rezaadi0105** [comment]
repo init -u git://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-10.0

**Comment by rezaadi0105** [comment]
Dont add space after git:

**Comment by xintiaoxuanlv** [comment]
> repo init -u git://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-10.0

I copy this link, or report an error

**Comment by xintiaoxuanlv** [comment]
> Dont add space after git:

what？

**Comment by manjotsidhu** [comment]
The correct command is
`repo init -u git://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-10.0`

Also no Authorization is required
